version: "3.1"

volumes:
  redis:
  postgres:

services:
  application:
    build: .
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:6
    volumes:
    - redis:/data
    ports:
    - 6379
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
      - ../log:/root/log
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PSQL_HISTFILE=/root/log/.psql_history
    ports:
      - 5432
